### Obetner las peliculas
GET http://localhost:1234/movies

### Obenter una pelicula pir id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Obtner una pelicula por genero
GET http://localhost:1234/movies?genre=action

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/7e4da58c-7271-4153-99f7-fdb755f3e8a8
Content-Type: application/json

{
  "year": 1972
}